name: Publish Release
on:
  release:
    types: [published]
jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Get tag version
        id: get_version
        run: echo ::set-env name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Publish
        env:
          BINTRAY_USER: ${{ secrets.bintrayUsername }}
          BINTRAY_PASS: ${{ secrets.bintrayApiKey }}
        run: sbt "project microplay-lib" publish

      - name: Upload artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'microplay-lib/target/scala-*/*.jar|microplay-lib/target/scala-*/*.pom'
