on:
  release:
    types: [created]
name: Publish Release
jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Publish
        env:
          BINTRAY_USER: ${{ secrets.bintrayUsername }}
          BINTRAY_PASS: ${{ secrets.bintrayApiKey }}
        run: sbt "project microplay-lib" publish
