name: Test

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '*.md'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Run tests
#    running it:test first since coverage data is being cleaned between these tasks and unit test coverage is more important - to bo fixed
      run: sbt "project microplay-lib" clean coverage it:test test coverageReport

    - name: Upload coverage report
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
#        file: microplay-lib/target/*/converage-report/covertura.xml
        flags: unittests
        name: codecov-microplay
        yml: ./codecov.yml
        fail_ci_if_error: true
